### ISSUE TITLE
Harmonize data types

### ISSUE THREAD

**Issue by linusonline** [AMSP-04/NETN-BASE#1]
I've made an effort to harmonize the use of some of the more generic data types in the FOM, such as ones for distance, speed, quantities, etc. I've aimed to move generic types to BASE whenever appropriate, make use of existing RPR types if appropriate, plus clarify semantics and give more precise names.

The issue that caused me to do this was a name collision between simple datatypes SpeedFloat32 and DegreesFloat32 that were both defined in METOC and ORG. Suggested changes in comment below, which resolves all data type name collisions.

**Comment by linusonline** [comment]
Propose the following changes:

- Add Simple data type ConcentrationKgPerMeterCubedFloat32
- Add Simple data type SpeedMeterPerSecondFloat32
- Add Simple data type PercentageUint32
- QuantityFloat32: clarify semantics
- Add Simple data type QuantityFloat64
- Add Simple data type QuantityInt32
- Rename data type TimeSecInt64 to EpochTimeSecInt64
- Add data type TimeSecInt32
- Add data type DirectionDegreesFloat32
- Add data type LatLongDegreesFloat64

**Comment by linusonline** [comment]
Proposed changes now pushed. Please reopen this issue if you disagree with the changes.

**Comment by lofstrandbjorn** [comment]
Included all proposals above and changes related to AMSP-04/NETN-MRM#4 Make MRM not depend on TMR and general changes to `modelIdentification`.

* Added Simple data type `ConcentrationKgPerMeterCubedFloat32`
* Added Simple data type `SpeedMeterPerSecondFloat32`
* Added Simple data type `PercentFloat64`
* Updated semantics of data type `QuantityFloat32`
* Added Simple data type `QuantityFloat64`
* Added Simple data type `QuantityInt32`
* Renamed data type `TimeSecInt64` to `EpochTimeSecInt64`
* Added data type `TimeSecInt32`
* Added data type `DirectionDegreesFloat32`
* Added data type `LatLongDegreesFloat64`

**Comment by lofstrandbjorn** [comment]
* Added Simple data type `ConcentrationKgPerMeterCubedFloat32`
* Added Simple data type `SpeedMeterPerSecondFloat32`
* Added Simple data type `PercentFloat64`
* Updated semantics of data type `QuantityFloat32`
* Added Simple data type `QuantityFloat64`
* Added Simple data type `QuantityInt32`
* Renamed data type `TimeSecInt64` to `EpochTimeSecInt64`
* Added data type `TimeSecInt32`
* Added data type `DirectionDegreesFloat32`
* Added data type `LatLongDegreesFloat64`
* Added datatype `FederateName` (from TMR).
* Added datatype `CancellationReasonEnum32` (from TMR).
* Added datatype `TransactionId` (from ETR and TMR).
* Changed `modelIdentification` `securityClassification` from `unclassified` to `Not Classified`
* Changed `modelIdentification` `other` to include license information
* Changed `modelIdentification` `useHistory` to only include formally relesed versions.

**Comment by bergtwvd** [comment]
- Added datatype `DegreesPerSecondFloat32`
- Added datatype `AltitudeMeterFloat64`
- Added datatype `IMOType`
- Added datatype `DraughtMeterFloat32`

**Comment by bergtwvd** [comment]
- Added datatype `MIDType`
- Added datatype `IMOType`
- Added datatype `ShipTypeType`

**Comment by bergtwvd** [comment]
Updated semantics of `EpochTimeSecInt64` for logical time.

**Comment by lofstrandbjorn** [comment]
* Added datatype `ArrayOfStringType`

**Comment by lofstrandbjorn** [comment]
* Added datatype `EchelonEnum32`
