### ISSUE TITLE
Remove deprecated datatype UuidArrayOfHLAbyte16

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-BASE#18]
Remove deprecated datatype UuidArrayOfHLAbyte16.
Is replaced by UUID,

**Comment by OscBer97** [comment]
All references to UuidArrayOfHLAbyte16 should be renamed to UUID now, see commits
872cdb92cf909566fdb58b3ab20d443bc38488e7
79c7be49430192c2fe55d2684eb0c623747ada0e
1ea2eb59345351f8f45641d67c5e198409a7f370
81d87c80a66f6578c5baa991693e29b951a2fba5
