### ISSUE TITLE
Generic datatypes for geographical features e.g. Path datatype

### ISSUE THREAD

**Issue by LennartOlsson** [AMSP-04/NETN-BASE#2]
A datatype for pathes is needed in NETN FOM modules. 
Add ArrayOfWorldLocationStruct2 in NETN-BASE.

**Comment by LennartOlsson** [comment]
Added the datatype.

**Comment by lofstrandbjorn** [comment]
There are other generic datatypes for Polygons, Paths, Circles, etc needed in the BASE module to support e.g. METOC module. I reopened this issue to harmonize the naming.

**Comment by lofstrandbjorn** [comment]
METOC uses GeodeticPoint, GeodeticPath and GeodeticCircle

**Comment by lofstrandbjorn** [comment]
* Renamed `ArrayOfWorldLocationStruct3` to `GeocentricPolygon`
* Renamed `ArrayOfWorldLocationStruct2` to `GeocentricPath`
* Added Array Datatpe `GeodeticPath`
* Added Array Datatpe `GeodeticPolygon`
* Added FixedRecord Datatype `GeodeticCircle`
* Added FixedRecord Datatype `GeodeticLocation`
* FixedRecord Datatype `GeodeticQuadrangle`
