### ISSUE TITLE
Harmonize Attribute/Parameter Names

### ISSUE THREAD

**Issue by LennartOlsson** [AMSP-04/NETN-BASE#3]
We need to harmonize the name on the unique identifier.

Suggestion: UniqueId, with exception for NETN-Physical and NETN-Aggregate where UniqueID is used since long time ago.

**Comment by lofstrandbjorn** [comment]
Identify where the changes need to be made and for existing modules (existing in NETN FOM v2.0) add issue, resolve and document changes in changelog.

**Comment by lofstrandbjorn** [comment]
Close this issue and create a new one on NETN FOM to address common schema for the naming of attributes for future versions of the NETN FOM.
