### ISSUE TITLE
Duplicate datatype

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-BASE#4]
NETN BASE: SpeedMeterPerSecondFloat32  (HLAfloat32BE, Meters per second)
RPR: VelocityMeterPerSecondFloat32 (HLAfloat32BE, meter per second (m/s))

I guess we should use the RPR.

**Comment by LennartOlsson** [comment]
Removed datatype from SpeedMeterPerSecondFloat32 (and updated NETN-ORG).
Closes this when the new version of NETN-BASE is uploaded.

**Comment by LennartOlsson** [comment]
Uploaded
