### ISSUE TITLE
Change TransactionId to UUID

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-BASE#7]
The assumption is that the TransactionId is created by an HLA federate, using its federateHandle and a local counter. A TransactionId may also be created by another application, not an HLA federate. For example, an application that connects to the simulation via the WebLVC protocol. Such an application does not have the federate handle. The proposal is to use a general approach, namely UUID to identify a transaction.

**Comment by lofstrandbjorn** [comment]
In principle I agree. If the impact is reasonable small we should implement this.

**Comment by bergtwvd** [comment]
In fact, for the CAXF demo we need to work-around the current FOM limitation and generate the federateHandle from the client name (the client is not an HLA federate). A Gateway and a WebLVC Server are two types of application that will benefit from this change.

**Comment by martin-s** [comment]
We also had discussions about this, especially in a gateway use case. The _FederateHandle_ should also be renamed in order to not solely cover the federate use case.

**Comment by lofstrandbjorn** [comment]
Are we in agreement to change to UUID ? Are there other datatypes with Federate Handle we should consider.

**Comment by bergtwvd** [comment]
Yes.  For any other places new issues will be created.

**Comment by lofstrandbjorn** [comment]
Changed to array datatype with UUID encoding and updated semantics accordingly. Same as UuidArrayOfHLAbyte16
